spring:
  application:
    name: henryshop-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.henryshop_api
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
logging:
  level:
    root: info